### ISSUE TITLE
🧐[问题]项目跑起来后 登陆后就停止运行了

### ISSUE THREAD

**Issue by ll21121** [jetlinks/jetlinks-ui-antd#250]
版本  1.9
node:v12.18.3
npm:6.14.6
系统 ：window10 64bit
开发环境，项目跑起来后 登陆后就停止运行了
异常信息:
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jetlinks@1.9.0 start: `umi dev UMI_UI=none`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jetlinks@1.9.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 请问下怎么解决

**Comment by linxiaodong0538** [comment]
我也是
