### ISSUE TITLE
🐛[BUG] F12报很多 unique "key" ，分支master

### ISSUE THREAD

**Issue by gogo1008** [jetlinks/jetlinks-ui-antd#794]
![image](https://user-images.githubusercontent.com/36293698/224472499-4133813c-edfc-43a2-9efd-c6b2159c247a.png)

Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at span
    at span
    at li
    at Item (http://localhost:8000/umi.js:845038:25)
    at RawItem (http://localhost:8000/umi.js:845500:52)
    at LegacyMenuItem (http://localhost:8000/umi.js:841568:87)
    at InternalMenuItem (http://localhost:8000/umi.js:841595:21)
    at MenuItem (http://localhost:8000/umi.js:841718:24)
    at Trigger (http://localhost:8000/umi.js:870534:89)
    at Tooltip (http://localhost:8000/umi.js:864899:32)
    at Tooltip (http://localhost:8000/umi.js:421431:62)
    at MenuItem (http://localhost:8000/umi.js:411248:87)
    at ul
    at Overflow (http://localhost:8000/umi.js:845158:32)
    at InheritableContextProvider (http://localhost:8000/umi.js:842461:23)
    at http://localhost:8000/umi.js:841075:27
    at http://localhost:8000/umi.js:411604:53
    at Menu (http://localhost:8000/umi.js:411712:87)
    at BaseMenu (http://localhost:8000/vendors-node_modules_ant-design_pro-layout_es_index_js-node_modules_umijs_route-utils_es_index_js.js:2303:21)
    at div
    at div
    at aside
    at Sider (http://localhost:8000/umi.js:409787:31)
    at SiderMenu (http://localhost:8000/vendors-node_modules_ant-design_pro-layout_es_index_js-node_modules_umijs_route-utils_es_index_js.js:2591:25)
    at SiderMenuWrapper (http://localhost:8000/vendors-node_modules_ant-design_pro-layout_es_index_js-node_modules_umijs_route-utils_es_index_js.js:2753:24)

**Comment by chengzichen** [comment]
我也碰见了,是什么问题,解决了吗?
